/*
%% -----------------------------------------------------------------------------
%%
%% grammar.ebnf: SQL - grammar definition in ebnf format.
%%
%% Copyright (c) 2012-17 K2 Informatics GmbH.  All Rights Reserved.
%%
%% This file is provided to you under the Apache License,
%% Version 2.0 (the "License"); you may not use this file
%% except in compliance with the License.  You may obtain
%% a copy of the License at
%%
%%   http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing,
%% software distributed under the License is distributed on an
%% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
%% KIND, either express or implied.  See the License for the
%% specific language governing permissions and limitations
%% under the License.
%%
%% -----------------------------------------------------------------------------
*/

/* =============================================================================
sql_list ->          sql ';' extra                                                              :         [{'$1','$3'}].
sql_list -> sql_list sql ';' extra                                                              : '$1' ++ [{'$2','$4'}].
============================================================================= */

sql_list ::= sql ';' ( extra )? ( sql ';' ( extra )? )*

/* =============================================================================
extra -> '$empty'                                                                               : {extra, <<>>}.
extra -> NAME  ';'                                                                              : {extra, unwrap_bin('$1')}.
============================================================================= */

extra ::= NAME  ';'

NAME ::= [A-Za-z][A-Za-z0-9_@:#\$]*

/* =============================================================================
sql -> procedure_call                                                                           : '$1'.
sql -> schema                                                                                   : '$1'.
sql -> cursor_def                                                                               : '$1'.
sql -> manipulative_statement                                                                   : '$1'.
sql -> WHENEVER NOT FOUND when_action                                                           : {'when_not_found', '$4'}.
sql -> WHENEVER SQLERROR when_action                                                            : {'when_sql_err', '$3'}.
============================================================================= */

sql ::= procedure_call
      | schema
      | cursor_def
      | manipulative_statement
      | 'WHENEVER' 'NOT' 'FOUND' when_action
      | 'WHENEVER' 'SQLERROR' when_action

/* =============================================================================
procedure_call -> DECLARE BEGIN function_ref_list END                                           : {'declare begin procedure', '$3'}.
procedure_call -> DECLARE BEGIN sql_list END                                                    : {'declare begin procedure', '$3'}.
procedure_call -> BEGIN function_ref_list END                                                   : {'begin procedure', '$2'}.
procedure_call -> BEGIN sql_list END                                                            : {'begin procedure', '$2'}.
procedure_call -> CALL function_ref                                                             : {'call procedure', '$2'}.
============================================================================= */

procedure_call ::= ( 'DECLARE' 'BEGIN' function_ref_list 'END' )
                 | ( 'DECLARE' 'BEGIN' sql_list          'END' )
                 | (           'BEGIN' function_ref_list 'END' )
                 | (           'BEGIN' sql_list          'END' )
                 | ( 'CALL' function_ref )

/* =============================================================================
function_ref_list -> function_ref ';'                                                           : ['$1'].
function_ref_list -> function_ref ';' function_ref_list                                         : ['$1' | '$3'].
============================================================================= */

function_ref_list ::= ( function_ref ';' )
                    | ( function_ref ';' function_ref_list )

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% schema definition language
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

sql -> schema                                                                                   : '$1'.

schema -> CREATE SCHEMA AUTHORIZATION NAME opt_schema_element_list                              : {'create schema authorization', unwrap('$4'), '$5'}.

opt_schema_element_list -> '$empty'                                                             : [].
opt_schema_element_list -> schema_element_list                                                  : '$1'.

schema_element_list ->                     schema_element                                       :         ['$1'].
schema_element_list -> schema_element_list schema_element                                       : '$1' ++ ['$2'].
============================================================================= */

schema ::= 'CREATE' 'SCHEMA' 'AUTHORIZATION' NAME ( schema_element ( schema_element )* )?

/* =============================================================================
schema_element -> create_role_def                                                               : '$1'.
schema_element -> create_table_def                                                              : '$1'.
schema_element -> create_index_def                                                              : '$1'.
schema_element -> create_user_def                                                               : '$1'.
schema_element -> view_def                                                                      : '$1'.
============================================================================= */

schema_element ::= create_role_def
                 | create_table_def
                 | create_index_def
                 | create_user_def
                 | view_def

/* =============================================================================
create_role_def -> CREATE ROLE NAME                                                             : {'create role', unwrap_bin('$3')}.
============================================================================= */

create_role_def ::= 'CREATE' 'ROLE' NAME

/* =============================================================================
create_table_def -> CREATE create_opts TABLE table '(' base_table_element_commalist ')'         : {'create table', '$4', '$6', '$2'}.
============================================================================= */

create_table_def ::= 'CREATE' ( tbl_scope )? ( tbl_type )? 'TABLE' table '(' ( base_table_element ( ',' base_table_element )* )? ')'

/* =============================================================================
create_user_def -> CREATE USER NAME identified opt_user_opts_list                               : {'create user', unwrap_bin('$3'), '$4', '$5'}.
============================================================================= */

create_user_def ::= 'CREATE' 'USER' NAME identified ( user_opt )*

/* =============================================================================
drop_table_def -> DROP      TABLE opt_exists table_list opt_restrict_cascade                    : {'drop table', {'tables', '$4'}, '$3', '$5', []}.
drop_table_def -> DROP NAME TABLE opt_exists table_list opt_restrict_cascade                    : {'drop table', {'tables', '$5'}, '$4', '$6', unwrap('$2')}.
============================================================================= */

drop_table_def ::= 'DROP' ( NAME )? 'TABLE' ( 'IF' 'EXISTS' )? ( table ( ',' table )* ) ( 'RESTRICT' | 'CASCADE' )?

/* =============================================================================
drop_role_def -> DROP ROLE NAME                                                                 : {'drop role', unwrap_bin('$3')}.
============================================================================= */

drop_role_def ::= 'DROP' 'ROLE' NAME

/* =============================================================================
drop_index_def -> DROP INDEX opt_index_name FROM table                                          : {'drop index', '$3', '$5'}.

opt_index_name -> '$empty'                                                                      : {}.
opt_index_name -> index_name                                                                    : '$1'.
============================================================================= */

drop_index_def ::= 'DROP' 'INDEX' ( index_name )? 'FROM' table

/* =============================================================================
create_index_def -> CREATE create_index_opts INDEX opt_index_name ON table create_index_spec create_index_opt_norm create_index_opt_filter
                                                                                                : {'create index', '$2', '$4', '$6', '$7', '$8', '$9'}.

create_index_opts -> '$empty'                                                                   : {}.
create_index_opts -> BITMAP                                                                     : bitmap.
create_index_opts -> KEYLIST                                                                    : keylist.
create_index_opts -> HASHMAP                                                                    : hashmap.
create_index_opts -> UNIQUE                                                                     : unique.

index_name -> NAME                                                                              : unwrap_bin('$1').
index_name -> NAME '.' NAME                                                                     : list_to_binary([unwrap('$1'), ".", unwrap('$3')]).
============================================================================= */

index_name ::= ( NAME '.' )? NAME

/* =============================================================================
create_index_spec -> '$empty'                                                                   : [].
create_index_spec -> '(' create_index_spec_items ')'                                            : '$2'.

create_index_spec_items -> NAME                                                                 : [unwrap_bin('$1')].
create_index_spec_items -> NAME '|' create_index_spec_items                                     : [unwrap_bin('$1') | '$3'].
create_index_spec_items -> JSON                                                                 : [{jp, jpparse('$1')}].
create_index_spec_items -> JSON '|' create_index_spec_items                                     : [{jp, jpparse('$1')} | '$3'].

create_index_opt_norm -> '$empty'                                                               : {}.
create_index_opt_norm -> NORM_WITH STRING                                                       : {norm, unwrap_bin('$2')}.

create_index_opt_filter -> '$empty'                                                             : {}.
create_index_opt_filter -> FILTER_WITH STRING                                                   : {filter, unwrap_bin('$2')}.
============================================================================= */

create_index_def ::= 'CREATE' ( 'BITMAP' | 'KEYLIST' | 'HASHMAP' | 'UNIQUE' )? 'INDEX' ( index_name )? 'ON' table ( '(' ( NAME | JSON ) ( '|' NAME | JSON )* ')' )?
                    ( 'NORM_WITH' STRING )?  ( 'FILTER_WITH' STRING )?

JSON ::= ([|] [:{\[#] [^|]+ [|])

STRING ::= ( 'fun' [A-Za-z0-9,_]* [.]* '->' [.]* 'end.' )
         | ( 'fun\s' ['A-Za-z0-9_]+ ':' ['A-Za-z0-9_]+ '/' [0-9]+ '.' )
         | ( "'" [^\']* "''**" )

/* =============================================================================
create_opts -> tbl_scope tbl_type                                                               : '$1' ++ '$2'.

tbl_scope -> '$empty'                                                                           : [].
tbl_scope -> LOCAL                                                                              : [{scope, <<"local">>}].
tbl_scope -> CLUSTER                                                                            : [{scope, <<"cluster">>}].
tbl_scope -> SCHEMA                                                                             : [{scope, <<"schema">>}].
============================================================================= */

tbl_scope ::= 'LOCAL'
            | 'CLUSTER'
            | 'SCHEMA'

/* =============================================================================
tbl_type -> '$empty'                                                                            : [].
tbl_type -> SET                                                                                 : [{type, <<"set">>}].
tbl_type -> ORDERED_SET                                                                         : [{type, <<"ordered_set">>}].
tbl_type -> BAG                                                                                 : [{type, <<"bag">>}].
tbl_type -> NAME                                                                                : [{type, unwrap_bin('$1')}].
============================================================================= */

tbl_type ::= 'SET'
           | 'ORDERED_SET'
           | 'BAG'
           | NAME

/* =============================================================================
alter_user_def -> ALTER USER user_list proxy_clause                                             : {'alter user', '$3', '$4'}.
alter_user_def -> ALTER USER NAME spec_list                                                     : {'alter user', unwrap_bin('$3'), {spec, '$4'}}.
alter_user_def -> ALTER USER NAME NAME NAME                                                     : {'alter user', unwrap_bin('$3'),
                                                                                                   {'spec',
                                                                                                    [case {string:to_lower(unwrap('$4')), string:to_lower(unwrap('$5'))} of
                                                                                                         {"account", "lock"} -> {account, lock};
                                                                                                         {"account", "unlock"} -> {account, unlock};
                                                                                                         {"password", "expire"} -> {password, expire};
                                                                                                         Unknown -> exit({invalid_option, Unknown})
                                                                                                     end]
                                                                                                   }
                                                                                                  }.
============================================================================= */

alter_user_def ::= ( 'ALTER' 'USER' NAME ( ',' NAME )* proxy_clause )
                 | ( 'ALTER' 'USER' NAME spec_item ( spec_item )* )
                 | ( 'ALTER' 'USER' NAME NAME NAME )

/* =============================================================================
drop_user_def -> DROP USER NAME                                                                 : {'drop user', unwrap_bin('$3'), []}.
drop_user_def -> DROP USER NAME CASCADE                                                         : {'drop user', unwrap_bin('$3'), ['cascade']}.
============================================================================= */

drop_user_def ::= 'DROP' 'USER' NAME ( 'CASCADE' )?

/* =============================================================================
user_list -> NAME                                                                               : [unwrap_bin('$1')].
user_list -> NAME ',' user_list                                                                 : [unwrap_bin('$1') | '$3'].

proxy_clause -> GRANT CONNECT THROUGH ENTERPRISE USERS                                          : {'grant connect', 'enterprise users'}.
proxy_clause -> GRANT CONNECT THROUGH db_user_proxy                                             : {'grant connect', '$4'}.
proxy_clause -> REVOKE CONNECT THROUGH ENTERPRISE USERS                                         : {'revoke connect', 'enterprise users'}.
proxy_clause -> REVOKE CONNECT THROUGH db_user_proxy                                            : {'revoke connect', '$4'}.
============================================================================= */

proxy_clause ::= ( 'GRANT' | 'REVOKE' ) 'CONNECT' 'THROUGH' ( ( 'ENTERPRISE' 'USERS' ) | db_user_proxy )

/* =============================================================================
db_user_proxy -> proxy_with                                                                     : '$1'.
db_user_proxy -> proxy_auth_req                                                                 : '$1'.
db_user_proxy -> proxy_with proxy_auth_req                                                      : {'$1', '$2'}.
============================================================================= */

db_user_proxy ::= proxy_with
                | ( ( proxy_with )? 'AUTHENTICATION' 'REQUIRED' )

/* =============================================================================
proxy_with -> WITH NO ROLES                                                                     : 'with no roles'.
proxy_with -> WITH ROLE role_list                                                               : {'with role', '$3'}.
proxy_with -> WITH ROLE ALL EXCEPT role_list                                                    : {'with role all except', '$5'}.

proxy_auth_req -> AUTHENTICATION REQUIRED                                                       : 'authentication required'.
============================================================================= */

proxy_with ::= ( 'WITH' 'NO' 'ROLES' )
             | ( 'WITH' 'ROLE' role_list )
             | ( 'WITH' 'ROLE' 'ALL' 'EXCEPT' role_list )

/* =============================================================================
spec_list -> spec_item                                                                          : ['$1'].
spec_list -> spec_item spec_list                                                                : ['$1'|'$2'].

spec_item -> identified                                                                         : '$1'.
spec_item -> user_opt                                                                           : '$1'.
spec_item -> user_role                                                                          : '$1'.
============================================================================= */

spec_item ::= identified
            | user_opt
            | user_role

/* =============================================================================
user_role -> DEFAULT ROLE ALL                                                                   : 'default role all'.
user_role -> DEFAULT ROLE ALL EXCEPT role_list                                                  : {'default role all except', '$5'}.
user_role -> DEFAULT ROLE NONE                                                                  : 'default role none'.
user_role -> DEFAULT ROLE role_list                                                             : {'default role', '$3'}.
============================================================================= */

user_role ::= 'DEFAULT' 'ROLE' ( ( 'ALL' ( 'EXCEPT' role_list )? ) | NONE | role_list )

/* =============================================================================
role_list -> NAME                                                                               : [unwrap_bin('$1')].
role_list -> NAME ',' role_list                                                                 : [unwrap_bin('$1') | '$3'].
============================================================================= */

role_list ::= NAME ( ',' NAME )*

/* =============================================================================
identified -> IDENTIFIED            BY NAME                                                     : {'identified by',       unwrap_bin('$3')}.
identified -> IDENTIFIED EXTERNALLY                                                             : {'identified extern',   {}}.
identified -> IDENTIFIED EXTERNALLY AS NAME                                                     : {'identified extern',   unwrap_bin('$4')}.
identified -> IDENTIFIED GLOBALLY                                                               : {'identified globally', {}}.
identified -> IDENTIFIED GLOBALLY   AS NAME                                                     : {'identified globally', unwrap_bin('$4')}.
============================================================================= */

identified ::= IDENTIFIED ( ( 'BY' NAME ) | ( EXTERNALLY ( 'AS' NAME ) ) | ( 'GLOBALLY' ( 'AS' NAME )? ) )

/* =============================================================================
opt_user_opts_list -> '$empty'                                                                  : [].
opt_user_opts_list -> user_opt opt_user_opts_list                                               : '$1' ++ '$2'.

user_opt -> DEFAULT TABLESPACE NAME                                                             : [{'default tablespace', unwrap_bin('$3')}].
user_opt -> TEMPORARY TABLESPACE NAME                                                           : [{'temporary tablespace', unwrap_bin('$3')}].
user_opt -> quota_list                                                                          : [{quotas, '$1'}].
user_opt -> PROFILE NAME                                                                        : [{profile, unwrap_bin('$2')}].
============================================================================= */

user_opt ::= ( ( 'DEFAULT' | 'TEMPORARY' ) 'TABLESPACE' NAME )
           | ( quota  ( quota )* )
           | ( 'PROFILE' NAME )

/* =============================================================================
quota_list -> quota                                                                             : ['$1'].
quota_list -> quota quota_list                                                                  : ['$1'] ++ '$2'.

quota -> QUOTA UNLIMITED   ON NAME                                                              : {'unlimited on', unwrap_bin('$4')}.
quota -> QUOTA INTNUM      ON NAME                                                              : {limited, unwrap_bin('$2'), unwrap_bin('$4')}.
quota -> QUOTA INTNUM NAME ON NAME                                                              : {limited, list_to_binary([unwrap('$2'),unwrap('$3')]),unwrap_bin('$5')}.
============================================================================= */

quota ::= ( 'QUOTA' 'UNLIMITED' 'ON' NAME )
        | ( 'QUOTA' INTNUM ( NAME )? 'ON' NAME )

INTNUM ::= ([0-9]+)

/* =============================================================================
table_list ->                table                                                              :         ['$1'].
table_list -> table_list ',' table                                                              : '$1' ++ ['$3'].

opt_exists -> '$empty'                                                                          : {}.
opt_exists -> IF EXISTS                                                                         : 'exists'.

opt_restrict_cascade -> '$empty'                                                                : {}.
opt_restrict_cascade -> RESTRICT                                                                : 'restrict'.
opt_restrict_cascade -> CASCADE                                                                 : 'cascade'.

base_table_element_commalist -> '$empty'                                                        : [].
base_table_element_commalist ->                                  base_table_element             :         ['$1'].
base_table_element_commalist -> base_table_element_commalist ',' base_table_element             : '$1' ++ ['$3'].

base_table_element -> column_def                                                                : '$1'.
base_table_element -> table_constraint_def                                                      : '$1'.
============================================================================= */

base_table_element ::= column_def
                     | table_constraint_def

/* =============================================================================
column_def -> column data_type column_def_opt_list                                              : {'$1', '$2', '$3'}.

column_def_opt_list -> '$empty'                                                                 : [].
column_def_opt_list -> column_def_opt_list column_def_opt                                       : '$1' ++ ['$2'].
============================================================================= */

column_def ::= column data_type ( column_def_opt )*

/* =============================================================================
column_def_opt -> NOT NULLX                                                                     : 'not null'.
column_def_opt -> NOT NULLX UNIQUE                                                              : 'not null unique'.
column_def_opt -> NOT NULLX PRIMARY KEY                                                         : 'not null primary key'.
column_def_opt -> DEFAULT function_ref                                                          : {default, '$2'}.
column_def_opt -> DEFAULT literal                                                               : {default, '$2'}.
column_def_opt -> DEFAULT NAME                                                                  : {default, unwrap_bin('$2')}.
column_def_opt -> DEFAULT NULLX                                                                 : {default, 'null'}.
column_def_opt -> DEFAULT USER                                                                  : {default, 'user'}.
column_def_opt -> CHECK '(' search_condition ')'                                                : {check, '$3'}.
column_def_opt -> REFERENCES table                                                              : {ref, '$2'}.
column_def_opt -> REFERENCES table '(' column_commalist ')'                                     : {ref, {'$2', '$4'}}.
============================================================================= */

column_def_opt ::= ( 'NOT' 'NULL' ( 'UNIQUE' | 'PRIMARY' 'KEY' )? )
                 | ( 'DEFAULT' ( function_ref | literal | NAME | 'NULL' | 'USER' ) )
                 | ( 'CHECK' '(' search_condition ')' )
                 | ( 'REFERENCES' table ( '(' column_commalist ')' )? )

/* =============================================================================
table_constraint_def -> UNIQUE '(' column_commalist ')'                                         : {unique, '$3'}.
table_constraint_def -> PRIMARY KEY '(' column_commalist ')'                                    : {'primary key', '$4'}.
table_constraint_def -> FOREIGN KEY '(' column_commalist ')' REFERENCES table                   : {'foreign key', '$4', {'ref', '$7'}}.
table_constraint_def -> FOREIGN KEY '(' column_commalist ')' REFERENCES table '(' column_commalist ')'
                                                                                                : {'foreign key', '$4', {'ref', {'$7', '$9'}}}.
table_constraint_def -> CHECK '(' search_condition ')'                                          : {check, '$3'}.
============================================================================= */

table_constraint_def ::= ( 'UNIQUE'        '(' column_commalist ')' )
                       | ( 'PRIMARY' 'KEY' '(' column_commalist ')' )
                       | ( 'FOREIGN' 'KEY' '(' column_commalist ')' 'REFERENCES' table ( '(' column_commalist ')' )? )
                       | ( 'CHECK' '(' search_condition ')' )

/* =============================================================================
column_commalist -> column                                                                      : ['$1'].
column_commalist -> column ',' column_commalist                                                 : ['$1' | '$3'].
============================================================================= */

column_commalist ::= column ( ',' column )*

/* =============================================================================
view_def -> CREATE VIEW table opt_column_commalist                                              : {'create view', '$3', '$4'}.
view_def -> AS query_spec                                                                       : {as, '$2', [],                   "as "}.
view_def -> AS query_spec WITH CHECK OPTION                                                     : {as, '$2', " with check option", "as "}.

opt_column_commalist -> '$empty'                                                                : [].
opt_column_commalist -> '(' column_commalist ')'                                                : {'$2', "("}.
============================================================================= */

view_def ::= ( 'CREATE' 'VIEW' table ( '(' column_commalist ')' )? )
           | ( 'AS' query_spec ( 'WITH' 'CHECK' 'OPTION' )? )

/* =============================================================================
grant_def -> GRANT system_privilege_list opt_on_obj_clause TO grantee_commalist opt_with_grant_option
                                                                                                : {grant, '$2', '$3', {to, '$5'}, '$6'}.
============================================================================= */

grant_def ::= 'GRANT' system_privilege_list ( on_obj_clause )? 'TO' grantee ( ',' grantee )* ( with_grant_option )?

/* =============================================================================
revoke_def -> REVOKE system_privilege_list opt_on_obj_clause FROM grantee_commalist opt_with_revoke_option
                                                                                                : {revoke, '$2', '$3', {from, '$5'}, '$6'}.
============================================================================= */

revoke_def ::= 'REVOKE' system_privilege_list ( on_obj_clause )? 'FROM' grantee ( ',' grantee )* ( with_revoke_option )?

/* =============================================================================
opt_on_obj_clause -> '$empty'                                                                   : {on, <<"">>}.
opt_on_obj_clause -> ON table                                                                   : {on, '$2'}.
opt_on_obj_clause -> ON DIRECTORY NAME                                                          : {'on directory',     unwrap_bin('$3')}.
opt_on_obj_clause -> ON JAVA SOURCE   table                                                     : {'on java source',   '$4'}.
opt_on_obj_clause -> ON JAVA RESOURCE table                                                     : {'on java resource', '$4'}.
============================================================================= */

on_obj_clause ::= ( 'ON' table )
                | ( 'ON' 'DIRECTORY' NAME )
                | ( 'ON' 'JAVA' ( 'SOURCE' | 'RESOURCE' ) table )

/* =============================================================================
system_privilege_list -> '$empty'                                                               : [].
system_privilege_list -> system_privilege                                                       : ['$1'].
system_privilege_list -> system_privilege ',' system_privilege_list                             : ['$1'|'$3'].
system_privilege_list -> ALL                                                                    : ['all'].
system_privilege_list -> ALL PRIVILEGES                                                         : ['all privileges'].
============================================================================= */

system_privilege_list ::= ( system_privilege ( ',' system_privilege )* )
                        | ( 'ALL' ( 'PRIVILEGES' )? )

/* =============================================================================
system_privilege -> SELECT                                                                      : 'select'.
system_privilege -> UPDATE                                                                      : 'update'.
system_privilege -> DELETE                                                                      : 'delete'.
system_privilege -> INSERT                                                                      : 'insert'.
system_privilege -> DROP                                                                        : 'drop'.
system_privilege -> NAME                                                                        : strl2atom(['$1']).
system_privilege -> NAME NAME                                                                   : strl2atom(['$1', '$2']).
system_privilege -> NAME NAME NAME                                                              : strl2atom(['$1', '$2', '$3']).
system_privilege -> NAME NAME NAME NAME                                                         : strl2atom(['$1', '$2', '$3', '$4']).
system_privilege -> NAME NAME NAME NAME NAME                                                    : strl2atom(['$1', '$2', '$3', '$4', '$5']).
============================================================================= */

system_privilege ::= 'SELECT'
                   | 'UPDATE'
                   | 'DELETE'
                   | 'INSERT'
                   | 'DROP'
                   | ( NAME ( NAME ( NAME ( NAME )? )? )? )

/* =============================================================================
opt_with_grant_option -> '$empty'                                                               : ''.
opt_with_grant_option -> WITH GRANT OPTION                                                      : 'with grant option'.
opt_with_grant_option -> WITH NAME OPTION                                                       : strl2atom(["with", '$2', "option"]).
opt_with_grant_option -> WITH HIERARCHY OPTION                                                  : 'with hierarchy option'.
============================================================================= */

with_grant_option ::= 'WITH' ( 'GRANT' | NAME | 'HIERARCHY' ) 'OPTION'

/* =============================================================================
opt_with_revoke_option -> '$empty'                                                              : ''.
opt_with_revoke_option -> CASCADE CONSTRAINTS                                                   : 'cascade constraints'.
opt_with_revoke_option -> FORCE                                                                 : 'force'.
============================================================================= */

with_revoke_option ::= ( 'CASCADE' 'CONSTRAINTS' )
                     | 'FORCE'

/* =============================================================================
grantee_commalist ->                       grantee                                              :         ['$1'].
grantee_commalist -> grantee_commalist ',' grantee                                              : '$1' ++ ['$3'].

grantee -> PUBLIC                                                                               : 'public'.
grantee -> NAME                                                                                 : unwrap_bin('$1').
grantee -> NAME IDENTIFIED BY NAME                                                              : {'identified by', unwrap_bin('$1'), unwrap_bin('$4')}.
============================================================================= */

grantee ::= 'PUBLIC'
          | ( NAME ( 'IDENTIFIED' 'BY' NAME )? )

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% cursor definition
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

sql -> cursor_def                                                                               : '$1'.

cursor_def -> DECLARE cursor CURSOR FOR query_exp opt_order_by_clause                           : {declare, '$2', {cur_for, '$5'}, '$6'}.
============================================================================= */

cursor_def ::= 'DECLARE' cursor 'CURSOR' 'FOR' query_exp ( order_by_clause )?

/* =============================================================================
opt_order_by_clause -> '$empty'                                                                 : {'order by', []}.
opt_order_by_clause -> ORDER BY ordering_spec_commalist                                         : {'order by', '$3'}.
============================================================================= */

order_by_clause ::= 'ORDER' 'BY' ordering_spec ( ',' ordering_spec )*

/* =============================================================================
ordering_spec_commalist ->                             ordering_spec                            :         ['$1'].
ordering_spec_commalist -> ordering_spec_commalist ',' ordering_spec                            : '$1' ++ ['$3'].

ordering_spec -> scalar_exp opt_asc_desc                                                        : {'$1', '$2'}.

opt_asc_desc -> '$empty'                                                                        : <<>>.
opt_asc_desc -> ASC                                                                             : <<"asc">>.
opt_asc_desc -> DESC                                                                            : <<"desc">>.
============================================================================= */

ordering_spec ::= scalar_exp ( 'ASC' | 'DESC' )?

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% manipulative statements
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

sql -> manipulative_statement                                                                   : '$1'.

manipulative_statement -> close_statement                                                       : '$1'.
manipulative_statement -> commit_statement                                                      : '$1'.
manipulative_statement -> delete_statement_positioned                                           : '$1'.
manipulative_statement -> delete_statement_searched                                             : '$1'.
manipulative_statement -> fetch_statement                                                       : '$1'.
manipulative_statement -> insert_statement                                                      : '$1'.
manipulative_statement -> open_statement                                                        : '$1'.
manipulative_statement -> rollback_statement                                                    : '$1'.
manipulative_statement -> select_statement                                                      : '$1'.
manipulative_statement -> update_statement_positioned                                           : '$1'.
manipulative_statement -> update_statement_searched                                             : '$1'.
manipulative_statement -> create_table_def                                                      : '$1'.
manipulative_statement -> create_role_def                                                       : '$1'.
manipulative_statement -> create_index_def                                                      : '$1'.
manipulative_statement -> create_user_def                                                       : '$1'.
manipulative_statement -> drop_role_def                                                         : '$1'.
manipulative_statement -> drop_table_def                                                        : '$1'.
manipulative_statement -> drop_index_def                                                        : '$1'.
manipulative_statement -> alter_user_def                                                        : '$1'.
manipulative_statement -> drop_user_def                                                         : '$1'.
manipulative_statement -> view_def                                                              : '$1'.
manipulative_statement -> truncate_table                                                        : '$1'.
manipulative_statement -> grant_def                                                             : '$1'.
manipulative_statement -> revoke_def                                                            : '$1'.
============================================================================= */

manipulative_statement ::= close_statement
                         | commit_statement
                         | delete_statement_positioned
                         | delete_statement_searched
                         | fetch_statement
                         | insert_statement
                         | open_statement
                         | rollback_statement
                         | select_statement
                         | update_statement_positioned
                         | update_statement_searched
                         | create_table_def
                         | create_role_def
                         | create_index_def
                         | create_user_def
                         | drop_role_def
                         | drop_table_def
                         | drop_index_def
                         | alter_user_def
                         | drop_user_def
                         | view_def
                         | truncate_table
                         | grant_def
                         | revoke_def

/* =============================================================================
truncate_table -> TRUNCATE TABLE table_name opt_materialized opt_storage                        : {'truncate table', '$3', '$4', '$5'}.

table_name -> NAME                                                                              : unwrap_bin('$1').
table_name -> NAME '.' NAME                                                                     : list_to_binary([unwrap('$1'),".",unwrap('$3')]).
table_name -> NAME '.' NAME '.' NAME                                                            : list_to_binary([unwrap('$1'),".",unwrap('$3'),".",unwrap('$5')]).
============================================================================= */

table_name ::= ( ( NAME '.' )? NAME '.' )? NAME

/* =============================================================================
opt_materialized -> '$empty'                                                                    : {}.
opt_materialized -> PRESERVE MATERIALIZED VIEW LOG                                              : {'materialized view log', 'preserve'}.
opt_materialized -> PURGE MATERIALIZED VIEW LOG                                                 : {'materialized view log', 'purge'}.

opt_storage ->  '$empty'                                                                        : {}.
opt_storage ->  DROP  STORAGE                                                                   : {storage, 'drop'}.
opt_storage ->  REUSE STORAGE                                                                   : {storage, 'reuse'}.
============================================================================= */

truncate_table ::= 'TRUNCATE' 'TABLE' table_name ( ( 'PRESERVE' | 'PURGE' ) 'MATERIALIZED' 'VIEW' 'LOG' )? ( ( 'DROP' | 'REUSE' ) 'STORAGE' )?

/* =============================================================================
close_statement -> CLOSE cursor                                                                 : {close, '$2'}.
============================================================================= */

close_statement ::= 'CLOSE' cursor

/* =============================================================================
commit_statement -> COMMIT                                                                      : 'commit'.
commit_statement -> COMMIT WORK                                                                 : 'commit work'.
============================================================================= */

commit_statement ::= 'COMMIT' ( 'WORK' )?

/* =============================================================================
delete_statement_positioned -> DELETE FROM table WHERE CURRENT OF cursor returning              : {delete, '$3',{where_current_of, '$7'}, '$8'}.
============================================================================= */

delete_statement_positioned ::= 'DELETE' 'FROM' table 'WHERE' 'CURRENT' 'OF' cursor ( returning )?

/* =============================================================================
delete_statement_searched -> DELETE FROM table opt_where_clause returning                       : {delete, '$3', '$4', '$5'}.
============================================================================= */

delete_statement_searched ::= 'DELETE' 'FROM' table ( where_clause )? ( returning )?

/* =============================================================================
fetch_statement -> FETCH cursor INTO target_commalist                                           : {fetch, '$2', {into, '$4'}}.
============================================================================= */

fetch_statement ::= 'FETCH' cursor 'INTO' target_commalist

/* =============================================================================
insert_statement -> INSERT INTO table                                                           : {insert, '$3', {}, {}, {}}.
insert_statement -> INSERT INTO table opt_column_commalist values_or_query_spec returning       : {insert, '$3', {cols, '$4'}, '$5', '$6'}.

values_or_query_spec -> VALUES '(' insert_atom_commalist ')'                                    : {values, '$3'}.
values_or_query_spec -> query_spec                                                              : '$1'.

insert_atom_commalist ->                           insert_atom                                  :         ['$1'].
insert_atom_commalist -> insert_atom_commalist ',' insert_atom                                  : '$1' ++ ['$3'].

insert_atom -> scalar_opt_as_exp                                                                : '$1'.
============================================================================= */

insert_statement ::= 'INSERT' 'INTO' table ( ( '(' column_commalist ')' )? ( ( 'VALUES' '(' scalar_opt_as_exp ( ',' scalar_opt_as_exp )* ')' ) | query_spec ) ( returning )? )?

/* =============================================================================
open_statement -> OPEN cursor                                                                   : {open, '$2'}.
============================================================================= */

open_statement ::= 'OPEN' cursor

/* =============================================================================
rollback_statement -> ROLLBACK                                                                  : 'rollback'.
rollback_statement -> ROLLBACK WORK                                                             : 'rollback work'.
============================================================================= */

rollback_statement ::= 'ROLLBACK' ( 'WORK' )?

/* =============================================================================
select_statement -> query_exp                                                                   : '$1'.
============================================================================= */

select_statement ::= query_exp

/* =============================================================================
opt_hint -> '$empty'                                                                            : {}.
opt_hint -> HINT                                                                                : {hints, unwrap_bin('$1')}.

opt_all_distinct -> '$empty'                                                                    : {}.
opt_all_distinct -> ALL                                                                         : {opt, <<"all">>}.
opt_all_distinct -> DISTINCT                                                                    : {opt, <<"distinct">>}.

update_statement_positioned -> UPDATE table SET assignment_commalist WHERE CURRENT OF cursor returning
                                                                                                : {update, '$2', {set, '$4'}, {where_current_of, '$8'}, '$9'}.
============================================================================= */

update_statement_positioned ::= 'UPDATE' table 'SET' assignment_commalist 'WHERE' 'CURRENT' 'OF' cursor ( returning )?

/* =============================================================================
assignment_commalist ->                          assignment                                     :         ['$1'].
assignment_commalist -> assignment_commalist ',' assignment                                     : '$1' ++ ['$3'].
============================================================================= */

assignment_commalist ::= assignment ( ',' assignment )*

/* =============================================================================
assignment -> column COMPARISON scalar_opt_as_exp                                               : {'=', '$1', '$3'}.
============================================================================= */

assignment ::= column COMPARISON scalar_opt_as_exp

COMPARISON ::= ':=' | '=' | '<>' | '<' | '>' | '<=' | '>='

/* =============================================================================
update_statement_searched -> UPDATE table SET assignment_commalist opt_where_clause returning   : {update, '$2', {set, '$4'}, '$5', '$6'}.
============================================================================= */

update_statement_searched ::= 'UPDATE' table 'SET' assignment_commalist ( where_clause )? ( returning )?

/* =============================================================================
target_commalist ->                      target                                                 :         ['$1'].
target_commalist -> target_commalist ',' target                                                 : '$1' ++ ['$3'].
============================================================================= */

target_commalist ::= target ( ',' target )*

/* =============================================================================
target -> NAME                                                                                  : unwrap_bin('$1').
target -> parameter_ref                                                                         : '$1'.
============================================================================= */

target ::= NAME
         | parameter_ref

/* =============================================================================
opt_where_clause -> '$empty'                                                                    : {where, {}}.
opt_where_clause -> where_clause                                                                : '$1'.

opt_hierarchical_query_clause -> '$empty'                                                       : {'hierarchical query', {}}.
opt_hierarchical_query_clause -> hierarchical_query_clause                                      : '$1'.

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% query expressions
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

query_exp ->                     query_term                                                     : '$1'.
query_exp -> query_exp UNION     query_term                                                     : {union,       '$1', '$3'}.
query_exp -> query_exp UNION ALL query_term                                                     : {'union all', '$1', '$4'}.
query_exp -> query_exp INTERSECT query_term                                                     : {intersect,   '$1', '$3'}.
query_exp -> query_exp MINUS     query_term                                                     : {minus,       '$1', '$3'}.
============================================================================= */

query_exp ::= query_term
            | ( query_exp ( ( 'UNION' ( 'ALL' )? ) | 'INTERSECT' | 'MINUS' ) query_term )

/* =============================================================================
returning -> '$empty'                                                                           : {returning, {}}.
returning -> RETURNING selection INTO selection                                                 : {returning, '$2', '$4'}.
returning -> RETURN    selection INTO selection                                                 : {return, '$2', '$4'}.
============================================================================= */

returning ::= ( 'RETURNING' | 'RETURN' ) selection 'INTO' selection

/* =============================================================================
query_term -> query_spec                                                                        : '$1'.
query_term -> '(' query_exp ')'                                                                 : {'$2', "("}.
============================================================================= */

query_term ::= query_spec
             | ( '(' query_exp ')' )

/* =============================================================================
query_spec -> SELECT opt_hint opt_all_distinct selection opt_into table_exp                     : {select,
                                                                                                   if '$2' == {} -> []; true -> ['$2'] end ++
                                                                                                   if '$3' == {} -> []; true -> ['$3'] end ++
                                                                                                   [{fields, '$4'}] ++
                                                                                                   if '$5' == {} -> []; true -> [{into, '$5'}] end ++
                                                                                                   '$6'}.

opt_into -> '$empty'                                                                            : {}.
opt_into -> INTO target_commalist                                                               : '$2'.
opt_into -> INTO target_commalist IN NAME                                                       : {'$2', {in, unwrap_bin('$4')}}.
============================================================================= */

query_spec ::= 'SELECT' ( HINT )? ( 'ALL' | 'DISTINCT' )? selection ( 'INTO' target_commalist ( 'IN' NAME )? )? table_exp

HINT ::= '/*' [^\*\/]* '*/'

/* =============================================================================
selection -> select_field_commalist                                                             : '$1'.
============================================================================= */

selection ::= select_field_commalist

/* =============================================================================
select_field -> case_when_opt_as_exp                                                            : ['$1'].
select_field -> scalar_opt_as_exp                                                               : ['$1'].
select_field -> '*'                                                                             : [<<"*">>].

select_field_commalist ->                            select_field                               :         ['$1'].
select_field_commalist -> select_field_commalist ',' select_field                               : '$1' ++ ['$3'].

case_when_opt_as_exp -> case_when_exp                                                           : '$1'.
case_when_opt_as_exp -> case_when_exp    NAME                                                   : {as, '$1', unwrap_bin('$2'), " "}.
case_when_opt_as_exp -> case_when_exp AS NAME                                                   : {as, '$1', unwrap_bin('$3'), " as "}.
============================================================================= */

select_field ::= ( case_when_exp ( ( 'AS' )? NAME )? )
               | scalar_opt_as_exp
               | '*'

select_field_commalist ::= select_field ( ',' select_field )*

/* =============================================================================
case_when_exp -> '(' case_when_exp ')'                                                          : {'$2', "("}.
case_when_exp -> CASE                   case_when_then_list opt_else END                        : {'case', <<>>, '$2', '$3'}.
case_when_exp -> CASE scalar_opt_as_exp case_when_then_list opt_else END                        : {'case', '$2', '$3', '$4'}.
============================================================================= */

case_when_exp ::= ( '(' case_when_exp ')' )
                | ( 'CASE' ( scalar_opt_as_exp )? case_when_then_list ( 'ELSE' scalar_opt_as_exp )? 'END' )

/* =============================================================================
case_when_then_list -> case_when_then                                                           : ['$1'].
case_when_then_list -> case_when_then case_when_then_list                                       : ['$1'|'$2'].
============================================================================= */

case_when_then_list ::= case_when_then ( case_when_then )*

/* =============================================================================
case_when_then -> WHEN search_condition THEN scalar_opt_as_exp                                  : {'$2', '$4'}.
============================================================================= */

case_when_then ::= 'WHEN' search_condition 'THEN' scalar_opt_as_exp

/* =============================================================================
opt_else -> '$empty'                                                                            : {}.
opt_else -> ELSE scalar_opt_as_exp                                                              : '$2'.

table_exp -> from_clause opt_where_clause
                         opt_hierarchical_query_clause
                         opt_group_by_clause
                         opt_having_clause
                         opt_order_by_clause                                                    : ['$1', '$2', '$3', '$4', '$5', '$6'].

from_clause -> FROM from_column_commalist                                                       : {from, '$2'}.

from_column -> table_ref                                                                        : ['$1'].
from_column -> '(' join_clause ')'                                                              : {['$2'], "("}.
from_column ->     join_clause                                                                  : ['$1'].

from_column_commalist ->                           from_column                                  :        ['$1'].
from_column_commalist -> from_column_commalist ',' from_column                                  : '$1'++ ['$3'].
============================================================================= */

from_column ::= table_ref
                 | ( '(' join_clause ')' )
                 | join_clause

table_exp ::= 'FROM' from_column ( from_column )* ( where_clause )? ( hierarchical_query_clause )? ( 'GROUP' 'BY' column_ref_commalist )? ( 'HAVING' search_condition )? ( order_by_clause )?

/* =============================================================================
join_clause -> table_ref join_list                                                              : {'$1', '$2'}.

join -> inner_cross_join                                                                        : '$1'.
join -> outer_join                                                                              : '$1'.

join_list ->           join                                                                     :        ['$1'].
join_list -> join_list join                                                                     : '$1'++ ['$2'].
============================================================================= */

join ::= inner_cross_join
       | outer_join

join_clause ::= table_ref join ( join )*

/* =============================================================================
inner_cross_join ->               JOIN join_ref join_on_or_using_clause                         : {join,               '$2', '$3'}.
inner_cross_join -> CROSS         JOIN join_ref                                                 : {cross_join,         '$3'}.
inner_cross_join -> INNER         JOIN join_ref join_on_or_using_clause                         : {join_inner,         '$3', '$4'}.
inner_cross_join -> NATURAL       JOIN join_ref                                                 : {natural_join,       '$3'}.
inner_cross_join -> NATURAL INNER JOIN join_ref                                                 : {natural_inner_join, '$4'}.
============================================================================= */

inner_cross_join ::= ( 'INNER' )? 'JOIN' join_ref join_on_or_using_clause
                   | ( 'CROSS' | ( 'NATURAL' ( 'INNER' )? ) ) 'JOIN' join_ref

/* =============================================================================
join_on_or_using_clause -> ON search_condition                                                  : {on, '$2'}.
join_on_or_using_clause -> USING '(' select_field_commalist ')'                                 : {using, '$3'}.
============================================================================= */

join_on_or_using_clause ::= ( 'ON' search_condition )
                          | ( 'USING' '(' select_field_commalist ')' )

/* =============================================================================
opt_join_on_or_using_clause -> '$empty'                                                         : {}.
opt_join_on_or_using_clause -> join_on_or_using_clause                                          : '$1'.

% ----------------------------------------------------------------------------------------------- {{join_type, partition, opt_natural} ... }
outer_join ->                                outer_join_type JOIN join_ref                        opt_join_on_or_using_clause
                                                                                                : {{'$1', {}, {}}, '$3', {}, '$4'}.
outer_join ->                                outer_join_type JOIN join_ref query_partition_clause opt_join_on_or_using_clause
                                                                                                : {{'$1', {}, {}}, '$3', '$4', '$5'}.
outer_join -> NATURAL                        outer_join_type JOIN join_ref                        opt_join_on_or_using_clause
                                                                                                : {{'$2', {}, natural}, '$4', {}, '$5'}.
outer_join -> NATURAL                        outer_join_type JOIN join_ref query_partition_clause opt_join_on_or_using_clause
                                                                                                : {{'$2', {}, natural}, '$4', '$5', '$6'}.
outer_join -> query_partition_clause         outer_join_type JOIN join_ref                        opt_join_on_or_using_clause
                                                                                                : {{'$2', '$1', {}}, '$4', {}, '$5'}.
outer_join -> query_partition_clause         outer_join_type JOIN join_ref query_partition_clause opt_join_on_or_using_clause
                                                                                                : {{'$2', '$1', {}}, '$4', '$5', '$6'}.
outer_join -> query_partition_clause NATURAL outer_join_type JOIN join_ref                        opt_join_on_or_using_clause
                                                                                                : {{'$3', '$1', natural}, '$5', {}, '$6'}.
outer_join -> query_partition_clause NATURAL outer_join_type JOIN join_ref query_partition_clause opt_join_on_or_using_clause
                                                                                                : {{'$3', '$1', natural}, '$5', '$6', '$7'}.
% -----------------------------------------------------------------------------------------------
============================================================================= */

outer_join ::= ( NATURAL | query_partition_clause | (query_partition_clause NATURAL) )? outer_join_type JOIN join_ref ( query_partition_clause )? ( join_on_or_using_clause )?

/* =============================================================================
query_partition_clause -> PARTITION BY     scalar_exp_commalist                                 : {partition_by, '$3', []} .
query_partition_clause -> PARTITION BY '(' scalar_exp_commalist ')'                             : {partition_by, '$4', "("}.
============================================================================= */

query_partition_clause ::= 'PARTITION' 'BY' ( ( '(' scalar_exp_commalist ')' ) | scalar_exp_commalist )

/* =============================================================================
outer_join_type -> FULL                                                                         : full.
outer_join_type -> FULL  OUTER                                                                  : full_outer.
outer_join_type -> LEFT                                                                         : left.
outer_join_type -> LEFT  OUTER                                                                  : left_outer.
outer_join_type -> RIGHT                                                                        : right.
outer_join_type -> RIGHT OUTER                                                                  : right_outer.
============================================================================= */

outer_join_type ::= ( 'FULL' ( 'OUTER' )? )
                  | ( 'LEFT' ( 'OUTER' )? )
                  | ( 'RIGHT' ( 'OUTER' )? )

/* =============================================================================
table_ref -> table                                                                              : '$1'.
table_ref -> table range_variable                                                               : {'$1', '$2'}.
table_ref -> '(' query_exp ')'                                                                  : {'$2', "("}.
table_ref -> '(' query_exp ')'    NAME                                                          : {as, {'$2', "("}, unwrap_bin('$4'), " "}.
table_ref -> '(' query_exp ')' AS NAME                                                          : {as, {'$2', "("}, unwrap_bin('$5'), " as "}.
============================================================================= */

table_ref ::= ( table ( range_variable )? )
            | ( '(' query_exp ')' ( ( 'AS' )? NAME )? )

/* =============================================================================
join_ref -> table                                                                               : '$1'.
join_ref -> '(' query_exp ')'                                                                   : {'$2', "("}.
join_ref -> '(' query_exp ')'    NAME                                                           : {as, {'$2', "("}, unwrap_bin('$4'), " "}.
join_ref -> '(' query_exp ')' AS NAME                                                           : {as, {'$2', "("}, unwrap_bin('$5'), " as "}.
============================================================================= */

join_ref ::= table
           | ( '(' query_exp ')' ( ( 'AS' )? NAME )? )

/* =============================================================================
hierarchical_query_clause -> START WITH search_condition CONNECT BY opt_nocycle search_condition: {'hierarchical query', {{'start with', '$3'}, {'connect by', '$6', '$7'}}}.
hierarchical_query_clause -> CONNECT BY opt_nocycle search_condition START WITH search_condition: {'hierarchical query', {{'connect by', '$3', '$4'}, {'start with', '$7'}}}.

opt_nocycle -> '$empty'                                                                         : <<>>.
opt_nocycle -> NOCYCLE                                                                          : <<"nocycle">>.
============================================================================= */

hierarchical_query_clause ::= ( 'START' 'WITH' search_condition 'CONNECT' 'BY' ( 'NOCYCLE' )? search_condition )
                            | ( 'CONNECT' 'BY' ( 'NOCYCLE' )? search_condition 'START' 'WITH' search_condition )

/* =============================================================================
where_clause -> WHERE search_condition                                                          : {where, '$2'}.
============================================================================= */

where_clause ::= 'WHERE' search_condition

/* =============================================================================
opt_group_by_clause  -> '$empty'                                                                : {'group by', []}.
opt_group_by_clause  -> GROUP BY column_ref_commalist                                           : {'group by', '$3'}.

column_ref_commalist ->                          column_ref                                     :         ['$1'].
column_ref_commalist ->                          function_ref                                   :         ['$1'].
column_ref_commalist -> column_ref_commalist ',' column_ref                                     : '$1' ++ ['$3'].
column_ref_commalist -> column_ref_commalist ',' function_ref                                   : '$1' ++ ['$3'].
============================================================================= */

column_ref_commalist ::= ( column_ref | function_ref ) ( ',' ( column_ref | function_ref ) )*

/* =============================================================================
opt_having_clause -> '$empty'                                                                   : {having, {}}.
opt_having_clause -> HAVING search_condition                                                    : {having, '$2'}.

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% search conditions
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

search_condition -> search_condition OR search_condition                                        : {'or', '$1', '$3'}.
search_condition -> search_condition AND search_condition                                       : {'and', '$1', '$3'}.
search_condition -> NOT search_condition                                                        : {'not', '$2'}.
search_condition -> '(' search_condition ')'                                                    : {'$2', "("}.
search_condition -> predicate                                                                   : '$1'.
============================================================================= */

search_condition ::= ( search_condition ( 'AND' | 'OR' ) search_condition )
                   | ( 'NOT' search_condition )
                   | ( '(' search_condition ')' )
                   | predicate

/* =============================================================================
predicate -> comparison_predicate                                                               : '$1'.
predicate -> between_predicate                                                                  : '$1'.
predicate -> like_predicate                                                                     : '$1'.
predicate -> test_for_null                                                                      : '$1'.
predicate -> in_predicate                                                                       : '$1'.
predicate -> all_or_any_predicate                                                               : '$1'.
predicate -> existence_test                                                                     : '$1'.
============================================================================= */

predicate ::= comparison_predicate
            | between_predicate
            | like_predicate
            | test_for_null
            | in_predicate
            | all_or_any_predicate
            | existence_test

/* =============================================================================
comparison_predicate -> scalar_opt_as_exp                                                       : '$1'.
comparison_predicate -> PRIOR scalar_exp COMPARISON scalar_exp                                  : {unwrap('$3'), {prior, '$2'}, '$4'}.
comparison_predicate -> scalar_exp COMPARISON PRIOR scalar_exp                                  : {unwrap('$2'), '$1', {prior, '$4'}}.
============================================================================= */

comparison_predicate ::= scalar_opt_as_exp
                       | ( ( 'PRIOR' )? scalar_exp COMPARISON scalar_exp )

/* =============================================================================
between_predicate -> scalar_exp not_between scalar_exp AND scalar_exp                           : {'not between', '$1', '$3', '$5'}.
between_predicate -> scalar_exp     BETWEEN scalar_exp AND scalar_exp                           : {between,       '$1', '$3', '$5'}.

not_between -> NOT BETWEEN                                                                      : 'not between'.
============================================================================= */

between_predicate ::= scalar_exp ( 'NOT' )? 'BETWEEN' scalar_exp 'AND' scalar_exp

/* =============================================================================
like_predicate -> scalar_exp not_like scalar_exp opt_escape                                     : {'not like', '$1', '$3', '$4'}.
like_predicate -> scalar_exp     LIKE scalar_exp opt_escape                                     : {like,       '$1', '$3', '$4'}.

not_like -> NOT LIKE                                                                            : 'not like'.

opt_escape  -> '$empty'                                                                         : <<>>.
opt_escape  -> ESCAPE atom                                                                      : '$2'.
============================================================================= */

like_predicate ::= scalar_exp ( 'NOT' )? 'LIKE' scalar_exp ( 'ESCAPE' atom )?

/* =============================================================================
test_for_null -> scalar_exp is_not_null                                                         : {'is not', '$1', <<"null">>}.
test_for_null -> scalar_exp is_null                                                             : {'is',     '$1', <<"null">>}.

is_not_null -> IS NOT NULLX                                                                     : 'is not'.

is_null -> IS NULLX                                                                             : is.
============================================================================= */

test_for_null ::= scalar_exp 'IS' ( 'NOT' )? 'NULL'

/* =============================================================================
in_predicate -> scalar_exp not_in '(' subquery ')'                                              : {'not in', '$1', '$4'}.
in_predicate -> scalar_exp     IN '(' subquery ')'                                              : {in,       '$1', '$4'}.
in_predicate -> scalar_exp not_in '(' scalar_exp_commalist ')'                                  : {'not in', '$1', {list, '$4'}}.
in_predicate -> scalar_exp     IN '(' scalar_exp_commalist ')'                                  : {in,       '$1', {list, '$4'}}.

not_in -> NOT IN                                                                                : 'not in'.
============================================================================= */

in_predicate ::= ( scalar_exp ( 'NOT' )? 'IN' '(' subquery ')' )
               | ( scalar_exp ( 'NOT' )? 'IN' '(' scalar_exp_commalist ')' )
               | ( scalar_exp ( 'NOT' )? 'IN' scalar_exp )

/* =============================================================================
all_or_any_predicate -> scalar_exp COMPARISON any_all_some subquery                             : {unwrap('$2'), '$1', {'$3', ['$4']}}.

any_all_some -> ANY                                                                             : 'any'.
any_all_some -> ALL                                                                             : 'all'.
any_all_some -> SOME                                                                            : 'some'.
============================================================================= */

all_or_any_predicate ::= scalar_exp COMPARISON ( 'ANY' | 'ALL' | 'SOME' ) subquery

/* =============================================================================
existence_test -> EXISTS subquery                                                               : {exists, '$2'}.
============================================================================= */

existence_test ::= 'EXISTS' subquery

/* =============================================================================
subquery -> query_exp                                                                           : '$1'.
============================================================================= */

subquery ::= query_exp

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% scalar expressions
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

scalar_opt_as_exp -> scalar_exp                                                                 : '$1'.
scalar_opt_as_exp -> scalar_exp COMPARISON scalar_exp                                           : {unwrap('$2'), '$1', '$3'}.
scalar_opt_as_exp -> scalar_exp    NAME                                                         : {as, '$1', unwrap_bin('$2'), " "}.
scalar_opt_as_exp -> scalar_exp AS NAME                                                         : {as, '$1', unwrap_bin('$3'), " as "}.
============================================================================= */

scalar_opt_as_exp ::= ( scalar_exp ( COMPARISON scalar_exp )? )
                    | ( scalar_exp ( AS )? NAME )

/* =============================================================================
scalar_exp -> scalar_sub_exp '||' scalar_exp                                                    : {'||','$1','$3'}.
scalar_exp -> scalar_sub_exp                                                                    : '$1'.
============================================================================= */

scalar_exp ::= scalar_sub_exp ( '||' scalar_exp )

/* =============================================================================
scalar_sub_exp -> scalar_sub_exp '+'    scalar_sub_exp                                          : {'+','$1','$3'}.
scalar_sub_exp -> scalar_sub_exp '-'    scalar_sub_exp                                          : {'-','$1','$3'}.
scalar_sub_exp -> scalar_sub_exp '*'    scalar_sub_exp                                          : {'*','$1','$3'}.
scalar_sub_exp -> scalar_sub_exp '/'    scalar_sub_exp                                          : {'/','$1','$3'}.
scalar_sub_exp -> scalar_sub_exp 'div'  scalar_sub_exp                                          : {'div','$1','$3'}.
scalar_sub_exp -> unary_add_or_subtract scalar_sub_exp                                          : {'$1','$2'}.
scalar_sub_exp -> NULLX                                                                         : <<"NULL">>.
scalar_sub_exp -> atom                                                                          : '$1'.
scalar_sub_exp -> subquery                                                                      : '$1'.
scalar_sub_exp -> column_ref                                                                    : '$1'.
scalar_sub_exp -> function_ref                                                                  : '$1'.
scalar_sub_exp -> '(' scalar_sub_exp ')'                                                        : {'$2', "("}.

unary_add_or_subtract -> '+'                                                                    : '+'.
unary_add_or_subtract -> '-'                                                                    : '-'.
============================================================================= */

scalar_sub_exp ::= ( scalar_sub_exp ( '+' | '-' | '*' | '/' | 'div' ) scalar_sub_exp )
                 | ( ( '+' | '-' ) scalar_sub_exp )
                 | 'NULL'
                 | atom
                 | subquery
                 | column_ref
                 | function_ref
                 | ( '(' scalar_sub_exp ')' )

/* =============================================================================
scalar_exp_commalist ->                          scalar_opt_as_exp                              :         ['$1'].
scalar_exp_commalist -> scalar_exp_commalist ',' scalar_opt_as_exp                              : '$1' ++ ['$3'].
============================================================================= */

scalar_exp_commalist ::= scalar_opt_as_exp ( ',' scalar_opt_as_exp )*

/* =============================================================================
atom -> parameter_ref                                                                           : '$1'.
atom -> literal                                                                                 : '$1'.
atom -> USER                                                                                    : <<"user">>.
============================================================================= */

atom ::= parameter_ref
       | literal
       | 'USER'

/* =============================================================================
parameter_ref -> parameter                                                                      : '$1'.
parameter_ref -> parameter parameter                                                            : {'$1', '$2'}.
parameter_ref -> parameter INDICATOR parameter                                                  : {indicator, '$1', '$3'}.
============================================================================= */

parameter_ref ::= parameter ( ( 'INDICATOR' )? parameter )?

/* =============================================================================
function_ref -> NAME '.' NAME '.' NAME '(' fun_args ')'                                         : {'fun', list_to_binary([unwrap('$1'),".",unwrap('$3'),".",unwrap('$5')]), make_list('$7')}.
function_ref -> NAME '.' NAME '(' fun_args ')'                                                  : {'fun', list_to_binary([unwrap('$1'),".",unwrap('$3')]),make_list('$5')}.
function_ref -> NAME '(' fun_args ')'                                                           : {'fun', unwrap_bin('$1'), make_list('$3')}.
function_ref -> FUNS                                                                            : {'fun', unwrap_bin('$1'), []}.
function_ref -> FUNS  '(' fun_args ')'                                                          : {'fun', unwrap_bin('$1'), make_list('$3')}.
function_ref -> FUNS   '(' '*' ')'                                                              : {'fun', unwrap_bin('$1'), [<<"*">>]}.
function_ref -> FUNS    '(' DISTINCT column_ref ')'                                             : {'fun', unwrap_bin('$1'), [{distinct, '$4'}]}.
function_ref -> FUNS     '(' ALL scalar_exp ')'                                                 : {'fun', unwrap_bin('$1'), [{all, '$4'}]}.
============================================================================= */

function_ref ::= ( ( ( NAME '.' )?  NAME '.' )? NAME '(' fun_args ')' )
               | ( 'FUNS' ( '(' ( fun_args | '*' | ( 'DISTINCT' column_ref ) | ( 'ALL' scalar_exp ) ) ')' )? )

/* =============================================================================
fun_args -> fun_arg                                                                             : ['$1'].
fun_args -> fun_arg ',' fun_args                                                                : ['$1' | '$3'].
============================================================================= */

fun_args ::= fun_arg ( ',' fun_arg )*

/* =============================================================================
fun_arg -> '(' fun_arg ')'                                                                      : {'$2', "("}.
fun_arg -> function_ref                                                                         : '$1'.
fun_arg -> column_ref                                                                           : '$1'.
fun_arg -> fun_arg '+' fun_arg                                                                  : {'+','$1','$3'}.
fun_arg -> fun_arg '-' fun_arg                                                                  : {'-','$1','$3'}.
fun_arg -> fun_arg '*' fun_arg                                                                  : {'*','$1','$3'}.
fun_arg -> fun_arg '/' fun_arg                                                                  : {'/','$1','$3'}.
fun_arg -> fun_arg 'div' fun_arg                                                                : {'div','$1','$3'}.
fun_arg -> fun_arg '||' fun_arg                                                                 : {'||','$1','$3'}.
fun_arg -> unary_add_or_subtract fun_arg                                                        : {'$1', '$2'}.
fun_arg -> NULLX                                                                                : <<"NULL">>.
fun_arg -> atom                                                                                 : '$1'.
fun_arg -> subquery                                                                             : '$1'.
fun_arg -> fun_arg AS NAME                                                                      : {as, '$1', unwrap_bin('$3')}.
fun_arg -> fun_arg COMPARISON fun_arg                                                           : {unwrap('$2'), '$1', '$3'}.
============================================================================= */

fun_arg ::= ( '(' fun_arg ')' )
          | function_ref
          | column_ref
          | ( fun_arg ( '+' | '-' | '*' | '/' | 'div' | '||' ) fun_arg )
          | ( ( '+' | '-' ) fun_arg )
          | 'NULL'
          | atom
          | subquery
          | ( fun_arg 'AS' NAME )
          | ( fun_arg COMPARISON fun_arg )

/* =============================================================================
literal -> STRING                                                                               : unwrap_bin('$1').
literal -> INTNUM                                                                               : unwrap_bin('$1').
literal -> APPROXNUM                                                                            : unwrap_bin('$1').
============================================================================= */

literal ::= STRING
          | INTNUM
          | APPROXNUM

APPROXNUM ::= ( ( '.' [0-9]+ ) | ( [0-9]+ '.'? [0-9]* ) ) ( [eE] [+-]? [0-9]+ )? [fFdD]?

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% miscellaneous
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

table -> NAME                                                                                   : unwrap_bin('$1').
table -> NAME AS NAME                                                                           : {as, unwrap_bin('$1'), unwrap_bin('$3'), " as "}.
table -> NAME    NAME                                                                           : {as, unwrap_bin('$1'), unwrap_bin('$2'), " "}.
table -> STRING                                                                                 : unwrap_bin('$1').
table -> NAME '.' NAME                                                                          : list_to_binary([unwrap('$1'),".",unwrap('$3')]).
table -> NAME '.' NAME AS NAME                                                                  : {as, list_to_binary([unwrap('$1'),".",unwrap('$3')]), unwrap_bin('$5'), " as "}.
table -> NAME '.' NAME    NAME                                                                  : {as, list_to_binary([unwrap('$1'),".",unwrap('$3')]), unwrap_bin('$4'), " "}.
table -> parameter                                                                              : '$1'.
table -> parameter    NAME                                                                      : {as, '$1', unwrap_bin('$2'), " "}.
table -> parameter AS NAME                                                                      : {as, '$1', unwrap_bin('$3'), " as "}.
============================================================================= */

table ::= ( ( NAME '.' )? NAME ( ( AS )? NAME )? )
        | STRING
        | ( parameter ( ( AS )? NAME )? )

/* =============================================================================
column_ref -> JSON                                                                              : {jp, jpparse('$1')}.
column_ref -> NAME     JSON                                                                     : {list_to_binary(unwrap('$1')), {jp,jpparse('$2')}}.
column_ref -> NAME '.' NAME     JSON                                                            : {list_to_binary([unwrap('$1'),".",unwrap('$3')]), {jp,jpparse('$4')}}.
column_ref -> NAME                                                                              : unwrap_bin('$1').
column_ref -> NAME '.' NAME                                                                     : list_to_binary([unwrap('$1'),".",unwrap('$3')]).
column_ref -> NAME '.' NAME '.' NAME                                                            : list_to_binary([unwrap('$1'),".",unwrap('$3'),".",unwrap('$5')]).
column_ref -> NAME '(' '+' ')'                                                                  : list_to_binary([unwrap('$1'),"(+)"]).
column_ref -> NAME '.' NAME '(' '+' ')'                                                         : list_to_binary([unwrap('$1'),".",unwrap('$3'),"(+)"]).
column_ref -> NAME '.' NAME '.' NAME '(' '+' ')'                                                : list_to_binary([unwrap('$1'),".",unwrap('$3'),".",unwrap('$5'),"(+)"]).
column_ref -> NAME '.' '*'                                                                      : list_to_binary([unwrap('$1'),".*"]).
column_ref -> NAME '.' NAME '.' '*'                                                             : list_to_binary([unwrap('$1'),".",unwrap('$3'),".*"]).
============================================================================= */

column_ref ::= ( ( ( NAME '.' )? NAME )? JSON )
             | ( ( ( NAME '.' )? NAME '.' )? NAME )
             | ( ( ( NAME '.' )? NAME '.' )? NAME '(' '+' ')' )
             | ( ( NAME '.' )? NAME '.' '*' )

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% data types
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

data_type -> STRING                                                                             : unwrap_bin('$1').
data_type -> NAME                                                                               : unwrap_bin('$1').
data_type -> NAME '(' opt_sgn_num ')'                                                           : {unwrap_bin('$1'), "(", '$3'}.
data_type -> NAME '(' opt_sgn_num ',' opt_sgn_num ')'                                           : {unwrap_bin('$1'), "(", '$3', '$5'}.
============================================================================= */

data_type ::= STRING
             | ( NAME ( '(' opt_sgn_num ')' )? )
             | ( NAME '(' opt_sgn_num ',' opt_sgn_num ')' )

/* =============================================================================
opt_sgn_num ->     INTNUM                                                                       : unwrap_bin('$1').
opt_sgn_num -> '-' INTNUM                                                                       : list_to_binary(["-",unwrap_bin('$2')]).
============================================================================= */

opt_sgn_num ::= ( '-' )? INTNUM

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% the various things you can name
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

column -> NAME                                                                                  : unwrap_bin('$1').
column -> STRING                                                                                : unwrap_bin('$1').
============================================================================= */

column ::= NAME
         | STRING

/* =============================================================================
cursor -> NAME                                                                                  : {cur, unwrap('$1')}.
============================================================================= */

cursor ::= NAME

/* =============================================================================
parameter -> PARAMETER                                                                          : {param, unwrap_bin('$1')}.
============================================================================= */

parameter ::= PARAMETER

PARAMETER ::= ':' [A-Za-z0-9_\.]+

/* =============================================================================
range_variable -> NAME                                                                          : unwrap_bin('$1').
============================================================================= */

range_variable ::= NAME

/* =============================================================================
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% embedded condition things
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

sql -> WHENEVER NOT FOUND when_action                                                           : {when_not_found, '$4'}.
sql -> WHENEVER SQLERROR when_action                                                            : {when_sql_err, '$3'}.

when_action -> GOTO NAME                                                                        : {goto, unwrap('$2')}.
when_action -> CONTINUE                                                                         : 'continue'.
============================================================================= */

when_action ::= ( 'GOTO' NAME )
              | 'CONTINUE'

/* ========================================================================== */
