name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: rebar3 steamroll --check
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 eunit
    - name: Run cover
      run: rebar3 cover
    - name: Run geas
      run: rebar3 as test geas
    - name: Coveralls
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: rebar3 as test coveralls send

